const map =[
    ["advertenciaDeUso","HpsaAtributosContenido1","Advertencia de uso","","","",""],
["alturaDeZocalo","HpsaAtributosContenido1","Altura de zócalo","","","",""],
["alturaMaximaProducto","HpsaAtributosContenido1","Altura máxima producto","","","",""],
["alturaMinimaReposabrazos","HpsaAtributosContenido1","Altura mínima reposabrazos","","","",""],
["arranqueEnCaliente","HpsaAtributosContenido1","Arranque en caliente","","","",""],
["autolimpiante","HpsaAtributosContenido1","Autolimpiante","","","",""],
["avances","HpsaAtributosContenido1","Avances","","","",""],
["camaraPrincipal","HpsaAtributosContenido1","Cámara principal","","","",""],
["cantidadDePaneles","HpsaAtributosContenido1","Cantidad de paneles","","","",""],
["capacidadDeCorteEnAluminio","HpsaAtributosContenido1","Capacidad de corte en aluminio","","","",""],
["capacidadDelCongelador","HpsaAtributosContenido1","Capacidad del congelador","","","",""],
["compatibilidadGriferia","HpsaAtributosContenido1","Compatibilidad grifería","","","",""],
["composicionQuimica","HpsaAtributosContenido1","Composición química","","","",""],
["consumoDeEnergia","HpsaAtributosContenido1","Consumo de energía","","","",""],
["dientesPorPulgada","HpsaAtributosContenido1","Dientes por pulgada","","","",""],
["discoDuroSolido","HpsaAtributosContenido1","Disco duro sólido","","","",""],
["exposicion","HpsaAtributosContenido1","Exposición","","","",""],
["formaDeSiembra","HpsaAtributosContenido1","Forma de siembra","","","",""],
["formatosDeReproduccion","HpsaAtributosContenido1","Formatos de reproducción","","","",""],
["hidroresistente","HpsaAtributosContenido1","Hidroresistente","","","",""],
["lavadoAVapor","HpsaAtributosContenido1","Lavado a vapor","","","",""],
["lentes3d","HpsaAtributosContenido1","Lentes 3D","","","",""],
["materialDeAislante","HpsaAtributosContenido1","Material de aislante","","","",""],
["materiales","HpsaAtributosContenido1","Materiales","","","",""],
["medidaDeProductosEnCombo","HpsaAtributosContenido1","Medida de productos en combo","","","",""],
["medidasDeCajones","HpsaAtributosContenido1","Medidas de cajones","","","",""],
["memoriaExpandible","HpsaAtributosContenido1","Memoria expandible","","","",""],
["metodoDeAplicacion","HpsaAtributosContenido1","Método de aplicación","","","",""],
["modeloDeMotor","HpsaAtributosContenido1","Modelo de motor","","","",""],
["numeroCertificadoEficienciaEne","HpsaAtributosContenido1","Número certificado eficiencia energética","","","",""],
["numeroDeDientes","HpsaAtributosContenido1","Número de dientes","","","",""],
["pedal","HpsaAtributosContenido1","Pedal","","","",""],
["protectorAntiruido","HpsaAtributosContenido1","Protector antiruido","","","",""],
["resolucionDePantalla","HpsaAtributosContenido1","Resolución de pantalla","","","",""],
["resolucionVideo","HpsaAtributosContenido1","Resolución video","","","",""],
["seguroParaNinos","HpsaAtributosContenido1","Seguro para niños","","","",""],
["seleccionDeTiempoDeSecado","HpsaAtributosContenido1","Selección de tiempo de secado","","","",""],
["sintonizadorDigital","HpsaAtributosContenido1","Sintonizador Digital","","","",""],
["sistema","HpsaAtributosContenido1","Sistema","","","",""],
["tapa","HpsaAtributosContenido1","Tapa","","","",""],
["tipoDeCampana","HpsaAtributosContenido1","Tipo de campana","","","",""],
["tipoDeChorros","HpsaAtributosContenido1","Tipo de chorros","","","",""],
["velocidadDelProcesador","HpsaAtributosContenido1","Velocidad del procesador","","","",""],
["visera","HpsaAtributosContenido1","Visera","","","",""],
["acabadoDeLaManija","HpsaAtributosContenido10","Acabado de la manija","","","",""],
["acabadoDePuertas","HpsaAtributosContenido10","Acabado de puertas","","","",""],
["acabadoDelVidrio","HpsaAtributosContenido10","Acabado del vidrio","","","",""],
["acolchado","HpsaAtributosContenido10","Acolchado","","","",""],
["antideslizante","HpsaAtributosContenido10","Antideslizante","","","",""],
["apoyaBrazos","HpsaAtributosContenido10","Apoya brazos","","","",""],
["bateria","HpsaAtributosContenido10","Batería","","","",""],
["bisagras","HpsaAtributosContenido10","Bisagras","","","",""],
["camaraIntegrada","HpsaAtributosContenido10","Cámara integrada","","","",""],
["cambioMecanico","HpsaAtributosContenido10","Cambio mecánico","","","",""],
["capacidadConductivaTermica","HpsaAtributosContenido10","Capacidad conductiva térmica","","","",""],
["composicionOrigen","HpsaAtributosContenido10","Composición/Origen","","","",""],
["compresor","HpsaAtributosContenido10","Compresor","","","",""],
["conexionWiFi","HpsaAtributosContenido10","Conexión Wi Fi","","","",""],
["depositoDeAguaDesmontable","HpsaAtributosContenido10","Depósito de agua desmontable","","","",""],
["dispensadorDeAgua","HpsaAtributosContenido10","Dispensador de agua","","","",""],
["distanciaEntrePuas","HpsaAtributosContenido10","Distancia entre púas","","","",""],
["espacioParaParlantes","HpsaAtributosContenido10","Espacio para parlantes","","","",""],
["espesorDeCuerpo","HpsaAtributosContenido10","Espesor de cuerpo","","","",""],
["giroDeCierre","HpsaAtributosContenido10","Giro de cierre","","","",""],
["lente","HpsaAtributosContenido10","Lente","","","",""],
["luzInterior","HpsaAtributosContenido10","Luz interior","","","",""],
["materialDeAsiento","HpsaAtributosContenido10","Material de asiento","","","",""],
["materialDelMango","HpsaAtributosContenido10","Material del mango","","","",""],
["materialDelTablero","HpsaAtributosContenido10","Material del tablero","","","",""],
["materialDeBroche","HpsaAtributosContenido10","Material  De Broche","","","",""],
["moldeable","HpsaAtributosContenido10","Moldeable","","","",""],
["numeroDePiezas","HpsaAtributosContenido10","Número de piezas","","","",""],
["numeroDeSillas","HpsaAtributosContenido10","Número de Sillas","","","",""],
["plazas","HpsaAtributosContenido10","Plazas","","","",""],
["porcentajeDeGerminacion","HpsaAtributosContenido10","Porcentaje de germinación","","","",""],
["proteccionUv","HpsaAtributosContenido10","Protección UV","","","",""],
["resolucionDeImagen","HpsaAtributosContenido10","Resolución de imagen","","","",""],
["retencionDeCompuestosQuimicos","HpsaAtributosContenido10","Retención de compuestos químicos","","","",""],
["reversible","HpsaAtributosContenido10","Reversible","","","",""],
["sistemaDeDescarga","HpsaAtributosContenido10","Sistema de descarga","","","",""],
["tamanoEntradaDeAire","HpsaAtributosContenido10","Tamaño entrada de aire","","","",""],
["tecladoIluminado","HpsaAtributosContenido10","Teclado iluminado","","","",""],
["tipoDeBoquillas","HpsaAtributosContenido10","Tipo de boquillas","","","",""],
["tipoDeFuncion","HpsaAtributosContenido10","Tipo de función","","","",""],
["tipoDeLaser","HpsaAtributosContenido10","Tipo de láser","","","",""],
["tipoDeMedidas","HpsaAtributosContenido10","Tipo de medidas","","","",""],
["tipoDeParrilla","HpsaAtributosContenido10","Tipo de parrilla","","","",""],
["tipoDeTablero","HpsaAtributosContenido10","Tipo de Tablero","","","",""],
["antiacaros","HpsaAtributosContenido11","Antiácaros","","","",""],
["autoperforante","HpsaAtributosContenido11","Autoperforante","","","",""],
["capacidadDePersonas","HpsaAtributosContenido11","Capacidad de personas","","","",""],
["colorDeAspas","HpsaAtributosContenido11","Color de aspas","","","",""],
["colorDeCuerpo","HpsaAtributosContenido11","Color de cuerpo","","","",""],
["colorDeLuz","HpsaAtributosContenido11","Color de luz","","","",""],
["controlDeLuz","HpsaAtributosContenido11","Control de luz","","","",""],
["correaAjustable","HpsaAtributosContenido11","Correa ajustable","","","",""],
["corteDeIngleteDeGradoMaximoDer","HpsaAtributosContenido11","Corte de inglete de grado máximo - derecha","","","",""],
["dispensadorDeHielo","HpsaAtributosContenido11","Dispensador de hielo","","","",""],
["epocaDeSiembra","HpsaAtributosContenido11","Época de siembra","","","",""],
["espacioParaDvdDecodificador","HpsaAtributosContenido11","Espacio para DVD/Decodificador","","","",""],
["flujoDeAireInverso","HpsaAtributosContenido11","Flujo de aire inverso","","","",""],
["formaDeLaTaza","HpsaAtributosContenido11","Forma de la taza","","","",""],
["formaDelPanel","HpsaAtributosContenido11","Forma del panel","","","",""],
["guiaLaser","HpsaAtributosContenido11","Guía láser","","","",""],
["ladoDeAbertura","HpsaAtributosContenido11","Lado de abertura","","","",""],
["materialDeLaEstructura","HpsaAtributosContenido11","Material de la estructura","","","",""],
["materialDeLasParrillas","HpsaAtributosContenido11","Material de las parrillas","","","",""],
["materialDeResorte","HpsaAtributosContenido11","Material de resorte","","","",""],
["memoriaInterna","HpsaAtributosContenido11","Memoria interna","","","",""],
["nivelDeProteccion","HpsaAtributosContenido11","Nivel de protección","","","",""],
["nivelesDePotencia","HpsaAtributosContenido11","Niveles de potencia","","","",""],
["numeroDeBandejas","HpsaAtributosContenido11","Número de bandejas","","","",""],
["numeroDeEntradasUsb","HpsaAtributosContenido11","Número de entradas USB","","","",""],
["numeroDeEntradasVideocomponent","HpsaAtributosContenido11","Número de entradas videocomponente","","","",""],
["numeroDeEstantes","HpsaAtributosContenido11","Número de estantes","","","",""],
["numeroDeHilos","HpsaAtributosContenido11","Número de hilos","","","",""],
["numeroDePerchas","HpsaAtributosContenido11","Número de perchas","","","",""],
["numeroDeProgramasDeLavado","HpsaAtributosContenido11","Número de programas de lavado","","","",""],
["numeroDeVelocidades","HpsaAtributosContenido11","Número de velocidades","","","",""],
["presionDeAgua","HpsaAtributosContenido11","Presión de agua","","","",""],
["punteraDeSeguridad","HpsaAtributosContenido11","Puntera de seguridad","","","",""],
["rebose","HpsaAtributosContenido11","Rebose","","","",""],
["reguladorDeTemperatura","HpsaAtributosContenido11","Regulador de temperatura","","","",""],
["resistenteALaCorrosion","HpsaAtributosContenido11","Resistente a la corrosión","","","",""],
["sistemaDeFuncionamiento","HpsaAtributosContenido11","Sistema de funcionamiento","","","",""],
["tamanoPantallaCelulares","HpsaAtributosContenido11","Tamaño pantalla celulares","","","",""],
["temporizador","HpsaAtributosContenido11","Temporizador","","","",""],
["tipoDeCorte","HpsaAtributosContenido11","Tipo de corte","","","",""],
["tipoDeEspacio","HpsaAtributosContenido11","Tipo de espacio","","","",""],
["tipoDeFoco","HpsaAtributosContenido11","Tipo de foco","","","",""],
["tipoDePerfil","HpsaAtributosContenido11","Tipo de perfil","","","",""],
["tipoDePiston","HpsaAtributosContenido11","Tipo de pistón","","","",""],
["tipoDeTecnologia","HpsaAtributosContenido11","Tipo de tecnología","","","",""],
["agenteExtintor","HpsaAtributosContenido12","Agente extintor","","","",""],
["alarmaDePuertaAbierta","HpsaAtributosContenido12","Alarma de puerta abierta","","","",""],
["cargadorDeBateria","HpsaAtributosContenido12","Cargador de batería","","","",""],
["cerrojoInferior","HpsaAtributosContenido12","Cerrojo inferior","","","",""],
["cloro","HpsaAtributosContenido12","Cloro","","","",""],
["colorDePuertas","HpsaAtributosContenido12","Color de puertas","","","",""],
["conexionBluetooth","HpsaAtributosContenido12","Conexión Bluetooth","","","",""],
["controlDeTemperatura","HpsaAtributosContenido12","Control de temperatura","","","",""],
["dielectrico","HpsaAtributosContenido12","Dieléctrico","","","",""],
["dualSim","HpsaAtributosContenido12","Dual SIM","","","",""],
["extensible","HpsaAtributosContenido12","Extensible","","","",""],
["formaDeBase","HpsaAtributosContenido12","Forma de base","","","",""],
["formaDelGrass","HpsaAtributosContenido12","Forma del grass","","","",""],
["formato","HpsaAtributosContenido12","Formato","","","",""],
["largoMinimo","HpsaAtributosContenido12","Largo mínimo","","","",""],
["ledIntegrado","HpsaAtributosContenido12","LED integrado","","","",""],
["mantenimientoDeFlujoLuminoso","HpsaAtributosContenido12","Mantenimiento de Flujo Luminoso","","","",""],
["marco","HpsaAtributosContenido12","Marco","","","",""],
["materialDeBisagras","HpsaAtributosContenido12","Material de bisagras","","","",""],
["materialDeCorrederas","HpsaAtributosContenido12","Material de correderas","","","",""],
["materialDeLaBarra","HpsaAtributosContenido12","Material de la barra","","","",""],
["numeroDeCombinaciones","HpsaAtributosContenido12","Número de combinaciones","","","",""],
["numeroDeCompartimientos","HpsaAtributosContenido12","Número de compartimientos","","","",""],
["numeroDeParrillasEnHorno","HpsaAtributosContenido12","Número de parrillas en horno","","","",""],
["numeroDePatas","HpsaAtributosContenido12","Número de patas","","","",""],
["pantallaSmart","HpsaAtributosContenido12","Pantalla smart","","","",""],
["pantallaTouch","HpsaAtributosContenido12","Pantalla touch","","","",""],
["plaga","HpsaAtributosContenido12","Plaga","","","",""],
["posavasos","HpsaAtributosContenido12","Posavasos","","","",""],
["puntosDeAbastecimientoEnSimult","HpsaAtributosContenido12","Puntos de abastecimiento en simultaneo","","","",""],
["reclinable","HpsaAtributosContenido12","Reclinable","","","",""],
["regualdorDeCaudal","HpsaAtributosContenido12","Regualdor de caudal","","","",""],
["remolcable","HpsaAtributosContenido12","Remolcable","","","",""],
["resistenciaALaAbrasion","HpsaAtributosContenido12","Resistencia a la abrasión","","","",""],
["resistenciaALaCompresion","HpsaAtributosContenido12","Resistencia a la compresión","","","",""],
["resistenciaAlImpacto","HpsaAtributosContenido12","Resistencia al impacto","","","",""],
["resistenciaAlMoho","HpsaAtributosContenido12","Resistencia al moho","","","",""],
["resistenciaRayosUv","HpsaAtributosContenido12","Resistencia rayos UV","","","",""],
["salvamotor","HpsaAtributosContenido12","Salvamotor","","","",""],
["talla","HpsaAtributosContenido12","Talla","","","",""],
["tipoDeBateria","HpsaAtributosContenido12","Tipo de batería","","","",""],
["tipoDeGrapa","HpsaAtributosContenido12","Tipo de grapa","","","",""],
["trinqueteReversible","HpsaAtributosContenido12","Trinquete reversible","","","",""],
["antiEmpanante","HpsaAtributosContenido13","Anti empañante","","","",""],
["antiInterferencia","HpsaAtributosContenido13","Anti interferencia","","","",""],
["autonomia","HpsaAtributosContenido13","Autonomía","","","",""],
["cabecera","HpsaAtributosContenido13","Cabecera","","","",""],
["capacidadDeElectrodo","HpsaAtributosContenido13","Capacidad de electrodo","","","",""],
["cerrojoSuperior","HpsaAtributosContenido13","Cerrojo superior","","","",""],
["concentracion","HpsaAtributosContenido13","Concentración","","","",""],
["conexionARedElectrica","HpsaAtributosContenido13","Conexión a red eléctrica","","","",""],
["dosisRecomendada","HpsaAtributosContenido13","Dosis recomendada","","","",""],
["envase","HpsaAtributosContenido13","Envase","","","",""],
["espesorMaximo","HpsaAtributosContenido13","Espesor máximo","","","",""],
["focoLuminiscente","HpsaAtributosContenido13","Foco luminiscente","","","",""],
["formaDelFoco","HpsaAtributosContenido13","Forma del foco","","","",""],
["gasRefrigerante","HpsaAtributosContenido13","Gas refrigerante","","","",""],
["indicadorDeTemperatura","HpsaAtributosContenido13","Indicador de temperatura","","","",""],
["inflable","HpsaAtributosContenido13","Inflable","","","",""],
["inflamable","HpsaAtributosContenido13","Inflamable","","","",""],
["manillas","HpsaAtributosContenido13","Manillas","","","",""],
["materialDeAcabado","HpsaAtributosContenido13","Material de acabado","","","",""],
["materialDeBaseDelCajon","HpsaAtributosContenido13","Material de base del cajón","","","",""],
["materialDeCerdas","HpsaAtributosContenido13","Material de cerdas","","","",""],
["materialDeCierre","HpsaAtributosContenido13","Material de cierre","","","",""],
["materialDeLaBandeja","HpsaAtributosContenido13","Material de la bandeja","","","",""],
["materialDeLaSalida","HpsaAtributosContenido13","Material de la salida","","","",""],
["numeroDeCuchillas","HpsaAtributosContenido13","Número de cuchillas","","","",""],
["numeroDeMelodias","HpsaAtributosContenido13","Número de melodías","","","",""],
["orientacion","HpsaAtributosContenido13","Orientación","","","",""],
["piezasPorCaja","HpsaAtributosContenido13","Piezas por caja","","","",""],
["porcentajeDePurificacion","HpsaAtributosContenido13","Porcentaje de purificación","","","",""],
["portafotos","HpsaAtributosContenido13","Portafotos","","","",""],
["proteccion","HpsaAtributosContenido13","Protección","","","",""],
["purificadorDeAire","HpsaAtributosContenido13","Purificador de aire","","","",""],
["recubrimientoDelMango","HpsaAtributosContenido13","Recubrimiento del mango","","","",""],
["retencionDeSolidosEnSuspension","HpsaAtributosContenido13","Retención de sólidos en suspensión","","","",""],
["sistemaOds","HpsaAtributosContenido13","Sistema ODS","","","",""],
["sistemaOperativo","HpsaAtributosContenido13","Sistema operativo","","","",""],
["tamanoDePua","HpsaAtributosContenido13","Tamaño de púa","","","",""],
["termocupla","HpsaAtributosContenido13","Termocupla","","","",""],
["tiempoDeUso","HpsaAtributosContenido13","Tiempo de uso","","","",""],
["tipoDeCarpa","HpsaAtributosContenido13","Tipo de carpa","","","",""],
["tipoDeConduccionTermica","HpsaAtributosContenido13","Tipo de conducción térmica","","","",""],
["tipoDeInodoro","HpsaAtributosContenido13","Tipo de inodoro","","","",""],
["tipoDeMotor","HpsaAtributosContenido13","Tipo de motor","","","",""],
["tipoDeTerminal","HpsaAtributosContenido13","Tipo de terminal","","","",""],
["vibracionesPorMinuto","HpsaAtributosContenido13","Vibraciones por minuto","","","",""],
["acabadoDelMarco","HpsaAtributosContenido14","Acabado del marco","","","",""],
["ajusteDePotencia","HpsaAtributosContenido14","Ajuste de potencia","","","",""],
["ambiente","HpsaAtributosContenido14","Ambiente","","","",""],
["aptoParaLavadora","HpsaAtributosContenido14","Apto para lavadora","","","",""],
["autoadhesivos","HpsaAtributosContenido14","Autoadhesivos","","","",""],
["centrifugado","HpsaAtributosContenido14","Centrifugado","","","",""],
["clasificacionAws","HpsaAtributosContenido14","Clasificación AWS","","","",""],
["dobleHoja","HpsaAtributosContenido14","Doble hoja","","","",""],
["espejo","HpsaAtributosContenido14","Espejo","","","",""],
["estadoDelContenido","HpsaAtributosContenido14","Estado del contenido","","","",""],
["estructuraInterna","HpsaAtributosContenido14","Estructura interna","","","",""],
["forma","HpsaAtributosContenido14","Forma","","","",""],
["hojaExtraible","HpsaAtributosContenido14","Hoja extraíble","","","",""],
["largoDelCarril","HpsaAtributosContenido14","Largo del carril","","","",""],
["materialDelTanque","HpsaAtributosContenido14","Material del tanque","","","",""],
["mecanismoDeApertura","HpsaAtributosContenido14","Mecanismo de apertura","","","",""],
["nivelDeCorrosion","HpsaAtributosContenido14","Nivel de corrosión","","","",""],
["nivelDeSeguridad","HpsaAtributosContenido14","Nivel de seguridad","","","",""],
["nombreCientifico","HpsaAtributosContenido14","Nombre científico","","","",""],
["numeroDeEntradasVga","HpsaAtributosContenido14","Número de entradas VGA","","","",""],
["plegable","HpsaAtributosContenido14","Plegable","","","",""],
["presionMinimaDeAguaDeAlimentac","HpsaAtributosContenido14","Presión mínima de agua de alimentación","","","",""],
["resistenteALaTranccion","HpsaAtributosContenido14","Resistente a la trancción","","","",""],
["reutilizable","HpsaAtributosContenido14","Reutilizable","","","",""],
["seguroDeBoton","HpsaAtributosContenido14","Seguro De Botón","","","",""],
["sistemaDeAutoregado","HpsaAtributosContenido14","Sistema de autoregado","","","",""],
["sistemaDeMarcoInterno","HpsaAtributosContenido14","Sistema de marco interno","","","",""],
["tarjetaDeVideo","HpsaAtributosContenido14","Tarjeta de video","","","",""],
["timbre","HpsaAtributosContenido14","Timbre","","","",""],
["tipoDeGriferia","HpsaAtributosContenido14","Tipo de Instalación De La Griferia","","","",""],
["tipoDeInstalacion","HpsaAtributosContenido14","Tipo de instalación","","","",""],
["tipoDePlanta","HpsaAtributosContenido14","Tipo de planta","","","",""],
["tipoDeSalida","HpsaAtributosContenido14","Tipo de salida","","","",""],
["tipoDeTejido","HpsaAtributosContenido14","Tipo de tejido","","","",""],
["trafico","HpsaAtributosContenido14","Tráfico","","","",""],
["tratamientoUv","HpsaAtributosContenido14","Tratamiento UV","","","",""],
["valvulaDeFuga","HpsaAtributosContenido14","Válvula de fuga","","","",""],
["velocidadDeTransferencia","HpsaAtributosContenido14","Velocidad de transferencia","","","",""],
["velocidadVariable","HpsaAtributosContenido14","Velocidad variable","","","",""],
["velocidades","HpsaAtributosContenido14","Velocidades","","","",""],
["arranqueEnFrio","HpsaAtributosContenido15","Arranque en frío","","","",""],
["capacidadDePesoDelTecho","HpsaAtributosContenido15","Capacidad de peso del techo","","","",""],
["capacidadDePesoPorRepisa","HpsaAtributosContenido15","Capacidad de peso por repisa","","","",""],
["diametroDeDistribucion","HpsaAtributosContenido15","Diámetro de distribución","","","",""],
["diametroDeSalida","HpsaAtributosContenido15","Diámetro de salida","","","",""],
["diametroInterno","HpsaAtributosContenido15","Diámetro interno","","","",""],
["diametroMaximoDePerforacionEnA","HpsaAtributosContenido15","Diámetro máximo de perforación en acero/metal","","","",""],
["flujoDeAire","HpsaAtributosContenido15","Flujo de aire","","","",""],
["gradoDeInclinacion","HpsaAtributosContenido15","Grado de inclinación","","","",""],
["impactosPorMinuto","HpsaAtributosContenido15","Impactos por minuto","","","",""],
["largoDeBarra","HpsaAtributosContenido15","Largo de barra","","","",""],
["largoDeLaHoja","HpsaAtributosContenido15","Largo de la hoja","","","",""],
["longitudDeCable","HpsaAtributosContenido15","Longitud de Cable","","","",""],
["mandril","HpsaAtributosContenido15","Mandril","","","",""],
["mantieneElAguaCalientePor","HpsaAtributosContenido15","Mantiene el agua caliente por","","","",""],
["materialDeTiradores","HpsaAtributosContenido15","Material de tiradores","","","",""],
["maximoFlujoDeAguaFiltrada","HpsaAtributosContenido15","Máximo flujo de agua filtrada","","","",""],
["medida","HpsaAtributosContenido15","Medida","","","",""],
["medidaDeLaLija","HpsaAtributosContenido15","Medida de la lija","","","",""],
["medidasDelTanque","HpsaAtributosContenido15","Medidas del tanque","","","",""],
["movimientosPorMinutoSpm","HpsaAtributosContenido15","Movimientos por minuto (spm)","","","",""],
["parDeGiroMaximo","HpsaAtributosContenido15","Par de giro máximo","","","",""],
["pesoDeLaCabeza","HpsaAtributosContenido15","Peso de la cabeza","","","",""],
["poderResidual","HpsaAtributosContenido15","Poder residual","","","",""],
["presionMaximaDeTrabajo","HpsaAtributosContenido15","Presión máxima de trabajo","","","",""],
["presionMinimaDeTrabajo","HpsaAtributosContenido15","Presión mínima de trabajo","","","",""],
["profundidadDeLaPoza","HpsaAtributosContenido15","Profundidad de la poza","","","",""],
["profundidadDeRebaje","HpsaAtributosContenido15","Profundidad de rebaje","","","",""],
["rangoDeAmperaje","HpsaAtributosContenido15","Rango de amperaje","","","",""],
["rendimiento","HpsaAtributosContenido15","Rendimiento","","","",""],
["tamanoDeHornillas","HpsaAtributosContenido15","Tamaño de hornillas","","","",""],
["tensionDelServicio","HpsaAtributosContenido15","Tensión del servicio","","","",""],
["tiempoDeAlmacenamiento","HpsaAtributosContenido15","Tiempo de almacenamiento","","","",""],
["tiempoDeCarga","HpsaAtributosContenido15","Tiempo de carga","","","",""],
["tipoDeMontaje","HpsaAtributosContenido15","Tipo de montaje","","","",""],
["tipoDeRefrigeradora","HpsaAtributosContenido15","Tipo De Refrigeradora","","","",""],
["torqueMaximo","HpsaAtributosContenido15","Torque máximo","","","",""],
["velocidad","HpsaAtributosContenido15","Velocidad","","","",""],
["velocidadSinCarga","HpsaAtributosContenido15","Velocidad sin carga","","","",""],
["voltaje","HpsaAtributosContenido15","Voltaje","","","",""],
["abrasividad","HpsaAtributosContenido16","Abrasividad","","","",""],
["alcance","HpsaAtributosContenido16","Alcance","","","",""],
["amperaje","HpsaAtributosContenido16","Amperaje","","","",""],
["anchoDePunta","HpsaAtributosContenido16","Ancho de punta","","","",""],
["aperturaMaxima","HpsaAtributosContenido16","Apertura Máxima","","","",""],
["areaDeCobertura","HpsaAtributosContenido16","Área de cobertura","","","",""],
["capacidad","HpsaAtributosContenido16","Capacidad","","","",""],
["capacidadDeCorte","HpsaAtributosContenido16","Capacidad de corte","","","",""],
["capacidadDeExtension","HpsaAtributosContenido16","Capacidad de extensión","","","",""],
["capacidadDePesoDeLaBase","HpsaAtributosContenido16","Capacidad de peso de la base","","","",""],
["capacidadDelTanque","HpsaAtributosContenido16","Capacidad del tanque","","","",""],
["caudal","HpsaAtributosContenido16","Caudal","","","",""],
["caudalMaximo","HpsaAtributosContenido16","Caudal máximo","","","",""],
["cicloVegetativo","HpsaAtributosContenido16","Ciclo vegetativo","","","",""],
["cri","HpsaAtributosContenido16","CRI","","","",""],
["diametro","HpsaAtributosContenido16","Diámetro","","","",""],
["diametroNominal","HpsaAtributosContenido16","Diámetro nominal","","","",""],
["drenaje","HpsaAtributosContenido16","Drenaje","","","",""],
["encastreYMedidas","HpsaAtributosContenido16","Encastre y medidas","","","",""],
["espesor","HpsaAtributosContenido16","Espesor","","","",""],
["frecuencia","HpsaAtributosContenido16","Frecuencia","","","",""],
["humedad","HpsaAtributosContenido16","% de Humedad","","","",""],
["largoDeLaMesa","HpsaAtributosContenido16","Largo de la mesa","","","",""],
["litrosPorDescarga","HpsaAtributosContenido16","Litros por descarga","","","",""],
["litrosPorMinuto","HpsaAtributosContenido16","Litros por minuto","","","",""],
["longitud","HpsaAtributosContenido16","Longitud","","","",""],
["lumenes","HpsaAtributosContenido16","Lúmenes","","","",""],
["mantenimientoDelFiltro","HpsaAtributosContenido16","Mantenimiento del filtro","","","",""],
["medidasDelDisco","HpsaAtributosContenido16","Medidas del disco","","","",""],
["potenciaDeHornillas","HpsaAtributosContenido16","Potencia de hornillas","","","",""],
["potenciaNominalDeEntrada","HpsaAtributosContenido16","Potencia nominal de entrada","","","",""],
["potenciaRealDeAspiracion","HpsaAtributosContenido16","Potencia real de aspiración","","","",""],
["precisionHpsa","HpsaAtributosContenido16","Precisión","","","",""],
["presionDeTrabajo","HpsaAtributosContenido16","Presión de trabajo","","","",""],
["resistencia","HpsaAtributosContenido16","Resistencia","","","",""],
["tamanoDeCuchilla","HpsaAtributosContenido16","Tamaño de cuchilla","","","",""],
["tasaDePercusion","HpsaAtributosContenido16","Tasa de percusión","","","",""],
["tdp","HpsaAtributosContenido16","TDP","","","",""],
["tiempoDeGerminacion","HpsaAtributosContenido16","Tiempo de germinación","","","",""],
["tiempoDeSecado","HpsaAtributosContenido16","Tiempo de secado","","","",""],
["alturaDelAsiento","HpsaAtributosContenido17","Altura del asiento","","","",""],
["alturaRecomendableDeDistribuci","HpsaAtributosContenido17","Altura recomendable de distribución","","","",""],
["anchoDeLaMesa","HpsaAtributosContenido17","Ancho de la mesa","","","",""],
["anchoReclinado","HpsaAtributosContenido17","Ancho reclinado","","","",""],
["capacidadDeFiltrado","HpsaAtributosContenido17","Capacidad de filtrado","","","",""],
["capacidadDePesoPorCanasta","HpsaAtributosContenido17","Capacidad de peso por canasta","","","",""],
["capacidadDelContenedor","HpsaAtributosContenido17","Capacidad del contenedor","","","",""],
["capacidadDelRecipiente","HpsaAtributosContenido17","Capacidad del recipiente","","","",""],
["capacidadTotalUtil","HpsaAtributosContenido17","Capacidad total útil","","","",""],
["coberturaDeRiego","HpsaAtributosContenido17","Cobertura de riego","","","",""],
["diametroDeSuccion","HpsaAtributosContenido17","Diámetro de succión","","","",""],
["diametroDelDisco","HpsaAtributosContenido17","Diámetro del disco","","","",""],
["diametroExterno","HpsaAtributosContenido17","Diámetro externo","","","",""],
["diametroMaximoDePerforacionEnM","HpsaAtributosContenido17","Diámetro máximo de perforación en madera","","","",""],
["dosificacion","HpsaAtributosContenido17","Dosificación","","","",""],
["edad","HpsaAtributosContenido17","Edad","","","",""],
["equivalenciaLuminosa","HpsaAtributosContenido17","Equivalencia luminosa","","","",""],
["flujoMaximo","HpsaAtributosContenido17","Flujo máximo","","","",""],
["fuerzaDeImpacto","HpsaAtributosContenido17","Fuerza de impacto","","","",""],
["horasDeDuracion","HpsaAtributosContenido17","Horas de duración","","","",""],
["inclinacionDelTrompo","HpsaAtributosContenido17","Inclinación del trompo","","","",""],
["largoDeLaManguera","HpsaAtributosContenido17","Largo de la manguera","","","",""],
["largoMaximo","HpsaAtributosContenido17","Largo máximo","","","",""],
["maximoDeSuccion","HpsaAtributosContenido17","Máximo de succión","","","",""],
["maximoPoderDeDescarga","HpsaAtributosContenido17","Máximo poder de descarga","","","",""],
["medidaDeEntradaDeAgua","HpsaAtributosContenido17","Medida de entrada de agua","","","",""],
["medidasLargoExtendida","HpsaAtributosContenido17","Medidas (largo extendida)","","","",""],
["medidasDelPanel","HpsaAtributosContenido17","Medidas del panel","","","",""],
["nivelDeRuido","HpsaAtributosContenido17","Nivel de ruido","","","",""],
["nivelesDeTemperatura","HpsaAtributosContenido17","Niveles de temperatura","","","",""],
["potencia","HpsaAtributosContenido17","Potencia","","","",""],
["potenciaHp","HpsaAtributosContenido17","Potencia HP","","","",""],
["profundidadMaximaDeCorte45","HpsaAtributosContenido17","Profundidad máxima de corte 45°","","","",""],
["rendimientoPorCaja","HpsaAtributosContenido17","Rendimiento por caja","","","",""],
["resistenciaMaximaVoltaje","HpsaAtributosContenido17","Resistencia máxima voltaje","","","",""],
["tamanoDeLaPantalla","HpsaAtributosContenido17","Tamaño de la pantalla","","","",""],
["temperaturaMaxima","HpsaAtributosContenido17","Temperatura máxima","","","",""],
["temperaturaMinima","HpsaAtributosContenido17","Temperatura mínima","","","",""],
["tiempoDeCalentamiento","HpsaAtributosContenido17","Tiempo de calentamiento","","","",""],
["voltajeDeSalida","HpsaAtributosContenido17","Voltaje De Salida","","","",""],
["altoConBase","HpsaAtributosContenido18","Alto con base","","","",""],
["alturaDeLaTaza","HpsaAtributosContenido18","Altura de la taza","","","",""],
["alturaDeReposabrazos","HpsaAtributosContenido18","Altura de reposabrazos","","","",""],
["alturaDeTablero","HpsaAtributosContenido18","Altura de tablero","","","",""],
["alturaMaximaReposabrazos","HpsaAtributosContenido18","Altura máxima reposabrazos","","","",""],
["anchoDeBase","HpsaAtributosContenido18","Ancho de base","","","",""],
["anchoDeCorte","HpsaAtributosContenido18","Ancho de corte","","","",""],
["btu","HpsaAtributosContenido18","BTU","","","",""],
["cajaRinde","HpsaAtributosContenido18","Caja rinde","","","",""],
["capacidadDeCarga","HpsaAtributosContenido18","Capacidad de carga","","","",""],
["capacidadDeCorteEnMadera","HpsaAtributosContenido18","Capacidad de corte en madera","","","",""],
["capacidadDeSecado","HpsaAtributosContenido18","Capacidad de secado","","","",""],
["capacidadDelTanqueDeCombustibl","HpsaAtributosContenido18","Capacidad del tanque de combustible","","","",""],
["cilindrada","HpsaAtributosContenido18","Cilindrada","","","",""],
["diametroDeDescarga","HpsaAtributosContenido18","Diámetro de descarga","","","",""],
["diametroDePivote","HpsaAtributosContenido18","Diámetro de pivote","","","",""],
["diametroMaximoDePerforacionEnM","HpsaAtributosContenido18","Diámetro máximo de perforación en mampostería","","","",""],
["diametroParaDesague","HpsaAtributosContenido18","Diámetro para desagüe","","","",""],
["distanciaDeInstalacion","HpsaAtributosContenido18","Distancia de instalación","","","",""],
["espesorDePuertas","HpsaAtributosContenido18","Espesor de puertas","","","",""],
["espesorDelVidrio","HpsaAtributosContenido18","Espesor del vidrio","","","",""],
["espesorMaximoDeCorte","HpsaAtributosContenido18","Espesor máximo de corte","","","",""],
["gradosDeApertura","HpsaAtributosContenido18","Grados de apertura","","","",""],
["largoDeLaFibra","HpsaAtributosContenido18","Largo de la fibra","","","",""],
["largoDeLaHelice","HpsaAtributosContenido18","Largo de la helice","","","",""],
["largoDelCable","HpsaAtributosContenido18","Largo del cable","","","",""],
["largoMaximoDeLaCadena","HpsaAtributosContenido18","Largo máximo de la cadena","","","",""],
["medidaDeReposabrazos","HpsaAtributosContenido18","Medida de reposabrazos","","","",""],
["metrosPorRollo","HpsaAtributosContenido18","Metros por rollo","","","",""],
["nivelesDeCoccion","HpsaAtributosContenido18","Niveles de cocción","","","",""],
["potenciaNominal","HpsaAtributosContenido18","Potencia nominal","","","",""],
["profundidadDeCompactacion","HpsaAtributosContenido18","Profundidad de compactación","","","",""],
["profundidadMaximaDeCorte90","HpsaAtributosContenido18","Profundidad máxima de corte 90°","","","",""],
["rendimientoDeSuperficieM2H","HpsaAtributosContenido18","Rendimiento de superficie (m2/h)","","","",""],
["resistenciaPorBandeja","HpsaAtributosContenido18","Resistencia por bandeja","","","",""],
["temperaturaMinimaDeTrabajo","HpsaAtributosContenido18","Temperatura mínima de trabajo","","","",""],
["tiempoDeDescarga","HpsaAtributosContenido18","Tiempo de descarga","","","",""],
["tiempoDeFuncionamientoALaMitad","HpsaAtributosContenido18","Tiempo de funcionamiento a la mitad de carga","","","",""],
["tiempoMaximoDeProgramacion","HpsaAtributosContenido18","Tiempo máximo de programación","","","",""],
["tiempoMinimoDeProgramacion","HpsaAtributosContenido18","Tiempo mínimo de programación","","","",""],
["alturaDeCerdas","HpsaAtributosContenido19","Altura de cerdas","","","",""],
["alturaDeLaBase","HpsaAtributosContenido19","Altura de la base","","","",""],
["alturaDeLaPlanta","HpsaAtributosContenido19","Altura de la planta","","","",""],
["alturaMaximaDeAlcance","HpsaAtributosContenido19","Altura máxima de alcance","","","",""],
["alturaMinimaProducto","HpsaAtributosContenido19","Altura mínima producto","","","",""],
["areaDeCoccion","HpsaAtributosContenido19","Área de cocción","","","",""],
["aro","HpsaAtributosContenido19","Aro","","","",""],
["capacidadDeLavado","HpsaAtributosContenido19","Capacidad de lavado","","","",""],
["diametroDelNylon","HpsaAtributosContenido19","Diámetro del nylon","","","",""],
["fuerzaDeSujecion","HpsaAtributosContenido19","Fuerza de sujeción","","","",""],
["largoDeLaEspada","HpsaAtributosContenido19","Largo de la espada","","","",""],
["medidaDelBrazo","HpsaAtributosContenido19","Medida del brazo","","","",""],
["presionNominalPn","HpsaAtributosContenido19","Presión nominal (pn)","","","",""],
["resistenciaEnKilos","HpsaAtributosContenido19","Resistencia en kilos","","","",""],
["temperaturaMaximaDeTrabajo","HpsaAtributosContenido19","Temperatura máxima de trabajo","","","",""],
["abrillantador","HpsaAtributosContenido2","Abrillantador","","","",""],
["aplicacion","HpsaAtributosContenido2","Aplicación","","","",""],
["aroma","HpsaAtributosContenido2","Aroma","","","",""],
["camaraFrontal","HpsaAtributosContenido2","Cámara frontal","","","",""],
["capacidadDePesoPorCajon","HpsaAtributosContenido2","Capacidad de peso por cajón","","","",""],
["capacidadDelHorno","HpsaAtributosContenido2","Capacidad del horno","","","",""],
["controlConVoz","HpsaAtributosContenido2","Control con voz","","","",""],
["controlDeHumedad","HpsaAtributosContenido2","Control de humedad","","","",""],
["diametroDeCanopla","HpsaAtributosContenido2","Diámetro de canopla","","","",""],
["distanciaEntreBisagras","HpsaAtributosContenido2","Distancia entre bisagras","","","",""],
["dondeUsarlo","HpsaAtributosContenido2","¿Dónde usarlo?","","","",""],
["duracionDeBateria","HpsaAtributosContenido2","Duración de batería","","","",""],
["enfriadorEnPuerta","HpsaAtributosContenido2","Enfriador en puerta","","","",""],
["espesorDeZocalo","HpsaAtributosContenido2","Espesor de zócalo","","","",""],
["funciones","HpsaAtributosContenido2","Funciones","","","",""],
["hidrorepelente","HpsaAtributosContenido2","Hidrorepelente","","","",""],
["interior","HpsaAtributosContenido2","Interior","","","",""],
["materialDeLaVisera","HpsaAtributosContenido2","Material de la visera","","","",""],
["materialDeTapaDeLaCubierta","HpsaAtributosContenido2","Material de tapa de la cubierta","","","",""],
["materialDelPlatoGiratorio","HpsaAtributosContenido2","Material del plato giratorio","","","",""],
["medidaDeLaBandeja","HpsaAtributosContenido2","Medida de la bandeja","","","",""],
["medidaDeLaPoza","HpsaAtributosContenido2","Medida de la poza","","","",""],
["medidaDeLaPuerta","HpsaAtributosContenido2","Medida de la puerta","","","",""],
["modeloDeTarjetaDeVideo","HpsaAtributosContenido2","Modelo de tarjeta de video","","","",""],
["modoDePreparacion","HpsaAtributosContenido2","Modo de preparación","","","",""],
["nivelDeDefinicion","HpsaAtributosContenido2","Nivel de definición","","","",""],
["norma","HpsaAtributosContenido2","Norma","","","",""],
["pasos","HpsaAtributosContenido2","Pasos","","","",""],
["platoGiratorio","HpsaAtributosContenido2","Plato Giratorio","","","",""],
["procesador","HpsaAtributosContenido2","Procesador","","","",""],
["programacion","HpsaAtributosContenido2","Programación","","","",""],
["propiedades","HpsaAtributosContenido2","Propiedades","","","",""],
["resistenciaMaximaImpacto","HpsaAtributosContenido2","Resistencia máxima impacto","","","",""],
["salanizado","HpsaAtributosContenido2","Salanizado","","","",""],
["sistemaAntiDesborde","HpsaAtributosContenido2","Sistema anti desborde","","","",""],
["sistemaInteractivo","HpsaAtributosContenido2","Sistema interactivo","","","",""],
["smartTv","HpsaAtributosContenido2","Smart TV","","","",""],
["tipoDeLavadero","HpsaAtributosContenido2","Tipo de lavadero","","","",""],
["tipoDePantalla","HpsaAtributosContenido2","Tipo de pantalla","","","",""],
["ubicacion","HpsaAtributosContenido2","Ubicación","","","",""],
["uso","HpsaAtributosContenido2","Uso","","","",""],
["aberturaFrontal","HpsaAtributosContenido3","Abertura frontal","","","",""],
["aireador","HpsaAtributosContenido3","Aireador","","","",""],
["antimicrobiano","HpsaAtributosContenido3","Antimicrobiano","","","",""],
["antiperforante","HpsaAtributosContenido3","Antiperforante","","","",""],
["asaTelescopica","HpsaAtributosContenido3","Asa telescópica","","","",""],
["autopropulsada","HpsaAtributosContenido3","Autopropulsada","","","",""],
["cantidadDePuertas","HpsaAtributosContenido3","Cantidad de puertas","","","",""],
["cartuchoReemplazable","HpsaAtributosContenido3","Cartucho reemplazable","","","",""],
["compatibilidad","HpsaAtributosContenido3","Compatibilidad","","","",""],
["condicionesDeInstalacion","HpsaAtributosContenido3","Condiciones de instalación","","","",""],
//["contenido","HpsaAtributosContenido3","Contenido","","","",""],
["controlDeVapor","HpsaAtributosContenido3","Control de vapor","","","",""],
["corteDeIngleteDeGradoMaximoIzq","HpsaAtributosContenido3","Corte de inglete de grado máximo - izquierda","","","",""],
["deodorizador","HpsaAtributosContenido3","Deodorizador","","","",""],
["diagnosticoInteligente","HpsaAtributosContenido3","Diagnóstico Inteligente","","","",""],
["diseno","HpsaAtributosContenido3","Diseño","","","",""],
["disenoDePuerta","HpsaAtributosContenido3","Diseño de Puerta","","","",""],
["distanciaEntrePerillas","HpsaAtributosContenido3","Distancia entre perillas","","","",""],
["duchaTelefono","HpsaAtributosContenido3","Ducha teléfono","","","",""],
["giratorio","HpsaAtributosContenido3","Giratorio","","","",""],
["gradoDeGiro","HpsaAtributosContenido3","Grado de giro","","","",""],
["mangoExtensible","HpsaAtributosContenido3","Mango extensible","","","",""],
["materialDeLaCabeza","HpsaAtributosContenido3","Material de la cabeza","","","",""],
["materialInternoDelAsiento","HpsaAtributosContenido3","Material interno del asiento","","","",""],
["materialInternoDelRespaldar","HpsaAtributosContenido3","Material interno del respaldar","","","",""],
["medidaDeBandejasORepisas","HpsaAtributosContenido3","Medida de bandejas o repisas","","","",""],
["medidasDeAlojamiento","HpsaAtributosContenido3","Medidas de alojamiento","","","",""],
["nombreComun","HpsaAtributosContenido3","Nombre común","","","",""],
["numeroDeAspas","HpsaAtributosContenido3","Número de aspas","","","",""],
["numeroDeEntradasHdmi","HpsaAtributosContenido3","Número de entradas HDMI","","","",""],
["numeroDePerforacionesParaGrife","HpsaAtributosContenido3","Número de perforaciones para grifería","","","",""],
["numeroDePiezasPorCaja","HpsaAtributosContenido3","Número de piezas por caja","","","",""],
["numeroDeRepisas","HpsaAtributosContenido3","Número de repisas","","","",""],
["potenciaDeExtraccion","HpsaAtributosContenido3","Potencia de extracción","","","",""],
["potenciaDeParlantes","HpsaAtributosContenido3","Potencia de parlantes","","","",""],
["recomendacionDeInstalacion","HpsaAtributosContenido3","Recomendación de instalación","","","",""],
["rotacion","HpsaAtributosContenido3","Rotación","","","",""],
["tipoDeCorredera","HpsaAtributosContenido3","Tipo de corredera","","","",""],
["tipoDeHorno","HpsaAtributosContenido3","Tipo de horno","","","",""],
["tipoDeMueble","HpsaAtributosContenido3","Tipo de mueble","","","",""],
["tipoDePuerta","HpsaAtributosContenido3","Tipo de puerta","","","",""],
["tipoDeQuemadores","HpsaAtributosContenido3","Tipo de quemadores","","","",""],
["usuario","HpsaAtributosContenido3","Usuario","","","",""],
["valvulaDeSeguridad","HpsaAtributosContenido3","Válvula de seguridad","","","",""],
["variedad","HpsaAtributosContenido3","Variedad","","","",""],
["ventajas","HpsaAtributosContenido3","Ventajas","","","",""],
["acabado","HpsaAtributosContenido4","Acabado","","","",""],
["agentePropulsor","HpsaAtributosContenido4","Agente propulsor","","","",""],
["agujeroParaLasPiernas","HpsaAtributosContenido4","Agujero para las piernas","","","",""],
["aislamientoDeSonido","HpsaAtributosContenido4","Aislamiento de sonido","","","",""],
["bolsaParaPolvo","HpsaAtributosContenido4","Bolsa para polvo","","","",""],
["botonUsoContinuo","HpsaAtributosContenido4","Botón uso continuo","","","",""],
["cantidadDeCanales","HpsaAtributosContenido4","Cantidad de canales","","","",""],
["cantidadDePerillas","HpsaAtributosContenido4","Cantidad de perillas","","","",""],
["cantidadDeResortes","HpsaAtributosContenido4","Cantidad de resortes","","","",""],
["categoriaCemento","HpsaAtributosContenido4","Categoría cemento","","","",""],
["cerrojoLateralInferior","HpsaAtributosContenido4","Cerrojo lateral inferior","","","",""],
["conexionATierra","HpsaAtributosContenido4","Conexión a tierra","","","",""],
["consumoDeAire","HpsaAtributosContenido4","Consumo de aire","","","",""],
["densidadUnitaria","HpsaAtributosContenido4","Densidad unitaria","","","",""],
["disponible","HpsaAtributosContenido4","Disponible","","","",""],
["estilo","HpsaAtributosContenido4","Estilo","","","",""],
["indicadorDeCombustible","HpsaAtributosContenido4","Indicador de combustible","","","",""],
["largoMinimoDeLaCadena","HpsaAtributosContenido4","Largo mínimo de la cadena","","","",""],
["materialDeHornillas","HpsaAtributosContenido4","Material de hornillas","","","",""],
["materialDeLaBase","HpsaAtributosContenido4","Material de la base","","","",""],
["materialDeLasPatas","HpsaAtributosContenido4","Material de las patas","","","",""],
["materialDeLasRuedas","HpsaAtributosContenido4","Material de las ruedas","","","",""],
["materialDeMandril","HpsaAtributosContenido4","Material de mandril","","","",""],
["materialDeRepisas","HpsaAtributosContenido4","Material de repisas","","","",""],
["memoriaRam","HpsaAtributosContenido4","Memoria RAM","","","",""],
["modoDeDescarga","HpsaAtributosContenido4","Modo de descarga","","","",""],
["numeroDeBarras","HpsaAtributosContenido4","Número de barras","","","",""],
["numeroDeColores","HpsaAtributosContenido4","Número de colores","","","",""],
["numeroDeEntradasRca","HpsaAtributosContenido4","Número de entradas RCA","","","",""],
["numeroDeJets","HpsaAtributosContenido4","Número de jets","","","",""],
["numeroDeLuces","HpsaAtributosContenido4","Número de luces","","","",""],
["numeroDePuertas","HpsaAtributosContenido4","Número de puertas","","","",""],
["numeroDePuertasPiston","HpsaAtributosContenido4","Número de puertas pistón","","","",""],
["perforaciones","HpsaAtributosContenido4","Perforaciones","","","",""],
["posabrazos","HpsaAtributosContenido4","Posabrazos","","","",""],
["procesadorDeComputo","HpsaAtributosContenido4","Procesador de cómputo","","","",""],
["puertaConPiston","HpsaAtributosContenido4","Puerta con pistón","","","",""],
["recargable","HpsaAtributosContenido4","Recargable","","","",""],
["reguladorDeAhorro","HpsaAtributosContenido4","Regulador de ahorro","","","",""],
["resistenteALaOxidacion","HpsaAtributosContenido4","Resistente a la oxidación","","","",""],
["rosticero","HpsaAtributosContenido4","Rosticero","","","",""],
["soporteDeParaguas","HpsaAtributosContenido4","Soporte de paraguas","","","",""],
["tipoDeConductor","HpsaAtributosContenido4","Tipo de conductor","","","",""],
["tipoDeEnergia","HpsaAtributosContenido4","Tipo de energía","","","",""],
["tipoDeLubricante","HpsaAtributosContenido4","Tipo de lubricante","","","",""],
["tipoDePulsador","HpsaAtributosContenido4","Tipo de pulsador","","","",""],
["tipoDeTirador","HpsaAtributosContenido4","Tipo de tirador","","","",""],
["ubicacionDeLaConexionDeAgua","HpsaAtributosContenido4","Ubicación de la conexión de agua","","","",""],
["vision","HpsaAtributosContenido4","Visión","","","",""],
["accesoFacilACarbones","HpsaAtributosContenido5","Acceso fácil a carbones","","","",""],
["adhesivo","HpsaAtributosContenido5","Adhesivo","","","",""],
["anticorte","HpsaAtributosContenido5","Anticorte","","","",""],
["aspasReversibles","HpsaAtributosContenido5","Aspas reversibles","","","",""],
["capacidadDelDiscoDuro","HpsaAtributosContenido5","Capacidad del disco duro","","","",""],
["cargadorIncluido","HpsaAtributosContenido5","Cargador incluído","","","",""],
["diluyente","HpsaAtributosContenido5","Diluyente","","","",""],
["disenoDePantalla","HpsaAtributosContenido5","Diseño de pantalla","","","",""],
["estantesAjustables","HpsaAtributosContenido5","Estantes ajustables","","","",""],
["expandible","HpsaAtributosContenido5","Expandible","","","",""],
["granos","HpsaAtributosContenido5","Granos","","","",""],
["hojaRetractil","HpsaAtributosContenido5","Hoja retráctil","","","",""],
["impermeable","HpsaAtributosContenido5","Impermeable","","","",""],
["inalambrico","HpsaAtributosContenido5","Inalámbrico","","","",""],
["magnetico","HpsaAtributosContenido5","Magnético","","","",""],
["materialDeLaMesa","HpsaAtributosContenido5","Material de la mesa","","","",""],
["materialDeLosSillones","HpsaAtributosContenido5","Material de los sillones","","","",""],
["materialDeRespaldar","HpsaAtributosContenido5","Material de respaldar","","","",""],
["materialDelTapiz","HpsaAtributosContenido5","Material del tapiz","","","",""],
["modoDeRegulacionNivelesDeCorte","HpsaAtributosContenido5","Modo de regulación niveles de corte","","","",""],
["nucleosDelProcesador","HpsaAtributosContenido5","Núcleos del procesador","","","",""],
["numeroDeCilindros","HpsaAtributosContenido5","Número de cilindros","","","",""],
["numeroDeFunciones","HpsaAtributosContenido5","Número de funciones","","","",""],
["numeroDeParrillas","HpsaAtributosContenido5","Número de parrillas","","","",""],
["numeroDePuntos10cm","HpsaAtributosContenido5","Número de puntos / 10cm","","","",""],
["oscilacionesSinCarga","HpsaAtributosContenido5","Oscilaciones sin carga","","","",""],
["regulable","HpsaAtributosContenido5","Regulable","","","",""],
["repisaParaTeclado","HpsaAtributosContenido5","Repisa para teclado","","","",""],
["resistenciaALaHumedad","HpsaAtributosContenido5","Resistencia a la humedad","","","",""],
["resistenciaALasRayaduras","HpsaAtributosContenido5","Resistencia a las rayaduras","","","",""],
["resistenteAlAgua","HpsaAtributosContenido5","Resistente al agua","","","",""],
["sistemaDeRefrigeracion","HpsaAtributosContenido5","Sistema de refrigeración","","","",""],
["tipoDeAjusteDeMandril","HpsaAtributosContenido5","Tipo de ajuste de mandril","","","",""],
["tipoDeBisagra","HpsaAtributosContenido5","Tipo de bisagra","","","",""],
["tipoDeClavo","HpsaAtributosContenido5","Tipo de clavo","","","",""],
["tipoDeDiscoDuro","HpsaAtributosContenido5","Tipo de disco duro","","","",""],
["tipoDeEncendido","HpsaAtributosContenido5","Tipo de encendido","","","",""],
["tipoDeEstructura","HpsaAtributosContenido5","Tipo de estructura","","","",""],
["tipoDePasador","HpsaAtributosContenido5","Tipo de pasador","","","",""],
["tipoDeProcesoDeSoldar","HpsaAtributosContenido5","Tipo de proceso de soldar","","","",""],
["tipoDeRack","HpsaAtributosContenido5","Tipo de rack","","","",""],
["tipoDeRecarga","HpsaAtributosContenido5","Tipo de recarga","","","",""],
["velocidadMaxima","HpsaAtributosContenido5","Velocidad máxima","","","",""],
["alturaAjustable","HpsaAtributosContenido6","Altura ajustable","","","",""],
["anodoDeMagnesio","HpsaAtributosContenido6","Ánodo de magnesio","","","",""],
["bloqueoDeSeguridad","HpsaAtributosContenido6","Bloqueo de seguridad","","","",""],
["calibre","HpsaAtributosContenido6","Calibre","","","",""],
["cantidadDeCuerpos","HpsaAtributosContenido6","Cantidad de cuerpos","","","",""],
["caudalDeChorroAjustable","HpsaAtributosContenido6","Caudal de chorro ajustable","","","",""],
["controlElectronicoDeVelocidad","HpsaAtributosContenido6","Control electrónico de velocidad","","","",""],
["desfogueDeAgua","HpsaAtributosContenido6","Desfogue de agua","","","",""],
["eficienciaEnergetica","HpsaAtributosContenido6","Eficiencia energética","","","",""],
["empunaduraAntiVibracion","HpsaAtributosContenido6","Empuñadura anti-vibración","","","",""],
["entradas","HpsaAtributosContenido6","Entradas","","","",""],
["extraccionDePolvo","HpsaAtributosContenido6","Extracción de polvo","","","",""],
["forrado","HpsaAtributosContenido6","Forrado","","","",""],
["fuenteDeAlimentacion","HpsaAtributosContenido6","Fuente de alimentación","","","",""],
["iluminacionLed","HpsaAtributosContenido6","Iluminación led","","","",""],
["lectorDeHuellas","HpsaAtributosContenido6","Lector de huellas","","","",""],
["lejia","HpsaAtributosContenido6","Lejía","","","",""],
["luzEnHorno","HpsaAtributosContenido6","Luz en horno","","","",""],
["materialDeBase","HpsaAtributosContenido6","Material De Base","","","",""],
["materialDeReposabrazos","HpsaAtributosContenido6","Material de reposabrazos","","","",""],
["materialDelFondo","HpsaAtributosContenido6","Material del fondo","","","",""],
["numeroDeEspejos","HpsaAtributosContenido6","Número de espejos","","","",""],
["numeroDeLlaves","HpsaAtributosContenido6","Número de llaves","","","",""],
["paredesAutolimpiantes","HpsaAtributosContenido6","Paredes autolimpiantes","","","",""],
["pasoDeLuz","HpsaAtributosContenido6","Paso de luz","","","",""],
["proporcionDeFallo","HpsaAtributosContenido6","Proporcion de Fallo","","","",""],
["puertasDesmontables","HpsaAtributosContenido6","Puertas desmontables","","","",""],
["requiereInstalacion","HpsaAtributosContenido6","Requiere instalación","","","",""],
["resistenciaSalina","HpsaAtributosContenido6","Resistencia salina","","","",""],
["sistemaDeApertura","HpsaAtributosContenido6","Sistema de apertura","","","",""],
["sistemaDeDrenado","HpsaAtributosContenido6","Sistema de drenado","","","",""],
["sistemaDeUnionDePiezas","HpsaAtributosContenido6","Sistema de unión de piezas","","","",""],
["sistemaOperativoCompatible","HpsaAtributosContenido6","Sistema operativo compatible","","","",""],
["superficie","HpsaAtributosContenido6","Superficie","","","",""],
["termostato","HpsaAtributosContenido6","Termostato","","","",""],
["textura","HpsaAtributosContenido6","Textura","","","",""],
["tipoDeCaida","HpsaAtributosContenido6","Tipo de caída","","","",""],
["tipoDeCocina","HpsaAtributosContenido6","Tipo de cocina","","","",""],
["tipoDeConexion","HpsaAtributosContenido6","Tipo de conexión","","","",""],
["tipoDeGas","HpsaAtributosContenido6","Tipo de gas","","","",""],
["tipoDeHoja","HpsaAtributosContenido6","Tipo de hoja","","","",""],
["tipoDeLuz","HpsaAtributosContenido6","Tipo de luz","","","",""],
["tipoDePanel","HpsaAtributosContenido6","Tipo de panel","","","",""],
["tipoDeVidrio","HpsaAtributosContenido6","Tipo de vidrio","","","",""],
["ajustable","HpsaAtributosContenido7","Ajustable","","","",""],
["antiInflamable","HpsaAtributosContenido7","Anti inflamable","","","",""],
["apagadoAutomatico","HpsaAtributosContenido7","Apagado automático","","","",""],
["botonDeAbertura","HpsaAtributosContenido7","Botón de abertura","","","",""],
["cabezaRegulable","HpsaAtributosContenido7","Cabeza regulable","","","",""],
["capacidadDeAbsorcion","HpsaAtributosContenido7","Capacidad de absorción","","","",""],
["cicloDeTrabajo","HpsaAtributosContenido7","Ciclo de trabajo","","","",""],
["corteMaximoEnDiagonal","HpsaAtributosContenido7","Corte máximo en diagonal","","","",""],
["extraccionDeHumedad","HpsaAtributosContenido7","Extracción de humedad","","","",""],
["genero","HpsaAtributosContenido7","Género","","","",""],
["grill","HpsaAtributosContenido7","Grill","","","",""],
["inversorIncorporado","HpsaAtributosContenido7","Inversor incorporado","","","",""],
["jetsHidromasajes","HpsaAtributosContenido7","Jets hidromasajes","","","",""],
["lavable","HpsaAtributosContenido7","Lavable","","","",""],
["luzPiloto","HpsaAtributosContenido7","Luz piloto","","","",""],
["mantenimiento","HpsaAtributosContenido7","Mantenimiento","","","",""],
["materialDeLaFunda","HpsaAtributosContenido7","Material de la funda","","","",""],
["materialDeRelleno","HpsaAtributosContenido7","Material de relleno","","","",""],
["materialDelCuerpo","HpsaAtributosContenido7","Material del cuerpo","","","",""],
["materialDelTambor","HpsaAtributosContenido7","Material del tambor","","","",""],
["numeroDeCajones","HpsaAtributosContenido7","Número de cajones","","","",""],
["numeroDeMotores","HpsaAtributosContenido7","Número de motores","","","",""],
["oscilante","HpsaAtributosContenido7","Oscilante","","","",""],
["posicionesDeEmpunadura","HpsaAtributosContenido7","Posiciones de empuñadura","","","",""],
["puertoEthernet","HpsaAtributosContenido7","Puerto ethernet","","","",""],
["pureza","HpsaAtributosContenido7","Pureza","","","",""],
["reguladorDePaseDeAgua","HpsaAtributosContenido7","Regulador de pase de agua","","","",""],
["reguladorDePresion","HpsaAtributosContenido7","Regulador de presión","","","",""],
["resistenciaALosSolventes","HpsaAtributosContenido7","Resistencia a los solventes","","","",""],
["resistenteACambiosDeTemperatur","HpsaAtributosContenido7","Resistente a cambios de temperatura","","","",""],
["resistenteAlFuego","HpsaAtributosContenido7","Resistente al fuego","","","",""],
["ruedas","HpsaAtributosContenido7","Ruedas","","","",""],
["tipoDeAcabado","HpsaAtributosContenido7","Tipo de acabado","","","",""],
["tipoDeAislamiento","HpsaAtributosContenido7","Tipo de aislamiento","","","",""],
["tipoDeBorde","HpsaAtributosContenido7","Tipo de borde","","","",""],
["tipoDeCilindro","HpsaAtributosContenido7","Tipo de cilindro","","","",""],
["tipoDeColor","HpsaAtributosContenido7","Tipo de Color","","","",""],
["tipoDeCorrederas","HpsaAtributosContenido7","Tipo de correderas","","","",""],
["tipoDePestillo","HpsaAtributosContenido7","Tipo de pestillo","","","",""],
["tipoDeRiego","HpsaAtributosContenido7","Tipo de riego","","","",""],
["tipoDeUso","HpsaAtributosContenido7","Tipo de uso","","","",""],
["wiFi","HpsaAtributosContenido7","Wi Fi","","","",""],
["accesoRemoto","HpsaAtributosContenido8","Acceso remoto","","","",""],
["acustico","HpsaAtributosContenido8","Acústico","","","",""],
["agarre","HpsaAtributosContenido8","Agarre","","","",""],
["aislamientoTermico","HpsaAtributosContenido8","Aislamiento térmico","","","",""],
["aislante","HpsaAtributosContenido8","Aislante","","","",""],
["alimentacionCombustible","HpsaAtributosContenido8","Alimentación/Combustible","","","",""],
["antiRayaduras","HpsaAtributosContenido8","Anti rayaduras","","","",""],
["camaraWeb","HpsaAtributosContenido8","Cámara web","","","",""],
["cantidadDePlacas","HpsaAtributosContenido8","Cantidad de placas","","","",""],
["capacidadConductivaElectrica","HpsaAtributosContenido8","Capacidad conductiva eléctrica","","","",""],
["cerraduraAuxiliar","HpsaAtributosContenido8","Cerradura auxiliar","","","",""],
["cerraduraLateralSuperior","HpsaAtributosContenido8","Cerradura lateral superior","","","",""],
["colorDeTablero","HpsaAtributosContenido8","Color de tablero","","","",""],
["compatibilidadConPiscinasDeSal","HpsaAtributosContenido8","Compatibilidad con piscinas de sal","","","",""],
["controlRemoto","HpsaAtributosContenido8","Control remoto","","","",""],
["convector","HpsaAtributosContenido8","Convector","","","",""],
["criterioDeDesgasteAc","HpsaAtributosContenido8","Criterio de desgaste (Ac)","","","",""],
["estabilizadorDeVoltaje","HpsaAtributosContenido8","Estabilizador de voltaje","","","",""],
["grado","HpsaAtributosContenido8","Grado","","","",""],
["hipoalergenico","HpsaAtributosContenido8","Hipoalergenico","","","",""],
["incluyeSombrilla","HpsaAtributosContenido8","Incluye sombrilla","","","",""],
["ip","HpsaAtributosContenido8","IP","","","",""],
["materialDeLaTela","HpsaAtributosContenido8","Material de la tela","","","",""],
["materialDeLasSillas","HpsaAtributosContenido8","Material de las sillas","","","",""],
["materialDeUso","HpsaAtributosContenido8","Material de uso","","","",""],
["materialDelMarco","HpsaAtributosContenido8","Material del marco","","","",""],
["numeroDeBolsillos","HpsaAtributosContenido8","Número de bolsillos","","","",""],
["numeroDeCiclos","HpsaAtributosContenido8","Número de ciclos","","","",""],
["numeroDeNiveles","HpsaAtributosContenido8","Número de niveles","","","",""],
["numeroDePozas","HpsaAtributosContenido8","Número de pozas","","","",""],
["numeroDeQuemadores","HpsaAtributosContenido8","Número de quemadores","","","",""],
["presentacion","HpsaAtributosContenido8","Presentación","","","",""],
["relleno","HpsaAtributosContenido8","Relleno","","","",""],
["resistenteALaHumedad","HpsaAtributosContenido8","Resistente a la humedad","","","",""],
["salidas","HpsaAtributosContenido8","Salidas","","","",""],
["termometro","HpsaAtributosContenido8","Termómetro","","","",""],
["tipoDeAgua","HpsaAtributosContenido8","Tipo de agua","","","",""],
["tipoDeAro","HpsaAtributosContenido8","Tipo de aro","","","",""],
["tipoDeCierre","HpsaAtributosContenido8","Tipo de cierre","","","",""],
["tipoDeFijacion","HpsaAtributosContenido8","Tipo de fijación","","","",""],
["tipoDeFiltro","HpsaAtributosContenido8","Tipo de filtro","","","",""],
["tipoDePunta","HpsaAtributosContenido8","Tipo de punta","","","",""],
["toxicidad","HpsaAtributosContenido8","Toxicidad","","","",""],
["ventilacion","HpsaAtributosContenido8","Ventilación","","","",""],
["vidrioTemplado","HpsaAtributosContenido8","Vidrio templado","","","",""],
["voltajeEnVacio","HpsaAtributosContenido8","Voltaje en vacío","","","",""],
["acabadoDeBorde","HpsaAtributosContenido9","Acabado de borde","","","",""],
["apilable","HpsaAtributosContenido9","Apilable","","","",""],
["aplicadorEnLaTapa","HpsaAtributosContenido9","Aplicador en la tapa","","","",""],
["apoyaBrazosRegulable","HpsaAtributosContenido9","Apoya brazos regulable","","","",""],
["cantidadDePivotes","HpsaAtributosContenido9","Cantidad de pivotes","","","",""],
["cantidadPorEmpaque","HpsaAtributosContenido9","Cantidad por empaque","","","",""],
["capacidadDeCorteEnAcero","HpsaAtributosContenido9","Capacidad de corte en acero","","","",""],
["cerraduraPrincipal","HpsaAtributosContenido9","Cerradura principal","","","",""],
["ciclos","HpsaAtributosContenido9","Ciclos","","","",""],
["consumoDeCombustible","HpsaAtributosContenido9","Consumo de combustible","","","",""],
["deteccionDeMovimiento","HpsaAtributosContenido9","Detección de movimiento","","","",""],
["diametroDePerforacion","HpsaAtributosContenido9","Diámetro de perforación","","","",""],
["escurridero","HpsaAtributosContenido9","Escurridero","","","",""],
["estandar","HpsaAtributosContenido9","Estándar","","","",""],
["filtroDePelusas","HpsaAtributosContenido9","Filtro de pelusas","","","",""],
["filtros","HpsaAtributosContenido9","Filtros","","","",""],
["flexible","HpsaAtributosContenido9","Flexible","","","",""],
["frecuenciaDeUso","HpsaAtributosContenido9","Frecuencia de uso","","","",""],
["freno","HpsaAtributosContenido9","Freno","","","",""],
["giroLateral","HpsaAtributosContenido9","Giro lateral","","","",""],
["incluyeTapaDeCubierta","HpsaAtributosContenido9","Incluye tapa de cubierta","","","",""],
["materialDeLosCojines","HpsaAtributosContenido9","Material de los cojines","","","",""],
["materialDePerillas","HpsaAtributosContenido9","Material de perillas","","","",""],
["materialDePuertas","HpsaAtributosContenido9","Material de puertas","","","",""],
["nivelesDeAgua","HpsaAtributosContenido9","Niveles de agua","","","",""],
["numeroDeNivelesDeCorte","HpsaAtributosContenido9","Número de niveles de corte","","","",""],
["numeroDeProgramasDeSecado","HpsaAtributosContenido9","Número de programas de secado","","","",""],
["portatil","HpsaAtributosContenido9","Portátil","","","",""],
["programas","HpsaAtributosContenido9","Programas","","","",""],
["proporcionMezcla","HpsaAtributosContenido9","Proporción mezcla","","","",""],
["reflectivo","HpsaAtributosContenido9","Reflectivo","","","",""],
["reguladorDeLlama","HpsaAtributosContenido9","Regulador de llama","","","",""],
["repisasRemovibles","HpsaAtributosContenido9","Repisas removibles","","","",""],
["requerimientoEspecial","HpsaAtributosContenido9","Requerimiento especial","","","",""],
["resistenciaAlFuego","HpsaAtributosContenido9","Resistencia al fuego","","","",""],
["resistenciaDialectrica","HpsaAtributosContenido9","Resistencia dieléctrica","","","",""],
["resistenteAlDesgaste","HpsaAtributosContenido9","Resistente al desgaste","","","",""],
["sistemaAntiGoteo","HpsaAtributosContenido9","Sistema anti goteo","","","",""],
["sistemaDeCierre","HpsaAtributosContenido9","Sistema de cierre","","","",""],
["tecnologiaCelular","HpsaAtributosContenido9","Tecnología celular","","","",""],
["timer","HpsaAtributosContenido9","Timer","","","",""],
["tipoDeCana","HpsaAtributosContenido9","Tipo de caña","","","",""],
["tipoDeCarga","HpsaAtributosContenido9","Tipo de carga","","","",""],
["tipoDePatas","HpsaAtributosContenido9","Tipo de patas","","","",""],
["tipoDeResortes","HpsaAtributosContenido9","Tipo de resortes","","","",""],
["tipoDeRosca","HpsaAtributosContenido9","Tipo de rosca","","","",""],
]
    
    module.exports={map}